#!/usr/bin/env node
/**
 * Generate MCP Servers Script
 * 
 * Generates MCP servers for Gopher and Finger protocols
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { YAMLParser } from '../src/core/yaml-parser.js';
import { ToolGenerator } from '../src/mcp/tool-generator.js';
import { ConfigGenerator } from '../src/mcp/config-generator.js';
import type { ProtocolSpec } from '../src/types/protocol-spec.js';

async function generateMCPServer(yamlPath: string, outputDir: string): Promise<void> {
  console.log(`\nGenerating MCP server for ${yamlPath}...`);
  
  // Read and parse YAML
  const yamlContent = await fs.readFile(yamlPath, 'utf-8');
  const parser = new YAMLParser();
  const spec = parser.parse(yamlContent);
  
  // Validate spec
  const validation = parser.validate(spec);
  if (!validation.valid) {
    throw new Error(`Invalid spec: ${validation.errors.join(', ')}`);
  }
  
  // Generate tools
  const toolGenerator = new ToolGenerator();
  const tools = toolGenerator.generateTools(spec);
  
  console.log(`  Generated ${tools.length} tools`);
  
  // Create output directory
  const protocolDir = path.join(outputDir, spec.protocol.name.toLowerCase());
  await fs.mkdir(protocolDir, { recursive: true });
  
  // Generate MCP server code
  const serverCode = generateServerCode(spec, tools);
  await fs.writeFile(path.join(protocolDir, 'mcp-server.ts'), serverCode);
  
  // Generate config
  const configGenerator = new ConfigGenerator();
  const config = configGenerator.generateConfig(spec);
  const configJson = configGenerator.generateConfigFile(config);
  await fs.writeFile(path.join(protocolDir, 'mcp.json'), configJson);
  
  console.log(`  ✓ Generated MCP server at ${protocolDir}/mcp-server.ts`);
  console.log(`  ✓ Generated config at ${protocolDir}/mcp.json`);
  
  return;
}

function generateServerCode(spec: ProtocolSpec, tools: any[]): string {
  const protocolName = spec.protocol.name;
  const toolsCode = tools.map(tool => `
    {
      name: '${tool.name}',
      description: '${tool.description}',
      inputSchema: ${JSON.stringify(tool.inputSchema, null, 6)},
      handler: async (args: any) => {
        // TODO: Implement actual protocol logic
        return {
          content: [{
            type: 'text',
            text: \`Executed ${tool.name} with args: \${JSON.stringify(args)}\`
          }]
        };
      }
    }`).join(',');
  
  return `/**
 * MCP Server for ${protocolName} Protocol
 * 
 * Generated by Protocol Resurrection Machine
 */

import { MCPServer } from '../../src/mcp/server-template.js';

const server = new MCPServer({
  name: '${protocolName}',
  version: '1.0.0',
  tools: [${toolsCode}
  ]
});

// Export for testing
export { server };

// Start server if run directly
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  console.log('${protocolName} MCP Server started');
  console.log(\`Tools: \${server.getRegistry().list().map(t => t.name).join(', ')}\`);
}
`;
}

async function main() {
  const outputDir = 'generated';
  
  // Generate for Gopher
  await generateMCPServer('protocols/gopher.yaml', outputDir);
  
  // Generate for Finger
  await generateMCPServer('protocols/finger.yaml', outputDir);
  
  console.log('\n✓ All MCP servers generated successfully!');
}

main().catch(error => {
  console.error('Error:', error);
  process.exit(1);
});
